### PR TITLE
c1 stev-dev

### PR DESCRIPTION
**Pull request by koffis-dev**
Steph regarde mon code s'il te plait.
Je pense qu'il peut être fusionné sur master

### CODE REVIEW

**Comment by koffindastephane** [comment]
Je suis au parc actuellement, je verifierai ton code dès que je rentre.

**Review by koffindastephane — APPROVED** [review]
The code is good.
Did you really need to use spring.jpa.database=MYSQL ?

**Comment by koffis-dev** [comment]
> The code is good.
> Did you really need to use spring.jpa.database=MYSQL ?



> The code is good.
> Did you really need to use spring.jpa.database=MYSQL ?

I think it's important for hibernate to generate sql code for MYSQL

**Comment by koffis-dev** [comment]
> > The code is good.
> > Did you really need to use spring.jpa.database=MYSQL ?
> 
> > The code is good.
> > Did you really need to use spring.jpa.database=MYSQL ?
> 
> I think it's important for hibernate to generate sql code for MYSQL

The PULL Request excecuted successfully

**Pull request merged**
